# Generated by Django 4.2.4 on 2023-09-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submission", "0073_track_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCccDeLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=400)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(null=True)),
                ("thumbnail_url", models.URLField(null=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_ccc_de_link",
                        to="submission.submission",
                    ),
                ),
            ],
        ),
    ]
