# Generated by Django 4.2.4 on 2023-09-26 14:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_media_ccc_de", "0001_initial"),
    ]

    operations = []
