name: Code Style

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pretalx_media_ccc_de/locale/**'
      - 'pretalx_media_ccc_de/static/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'pretalx_media_ccc_de/locale/**'
      - 'pretalx_media_ccc_de/static/**'


jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install isort
        run: pip3 install isort
      - name: Run isort
        run: isort -c .
  flake:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install Dependencies
        run: pip3 install flake8 flake8-bugbear
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Run flake8
        run: flake8 .
        working-directory: .
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install Dependencies
        run: pip3 install black
      - name: Run black
        run: black --check .
        working-directory: .
  djhtml:
    name: djhtml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install Dependencies
        run: pip3 install djhtml
      - name: Run docformatter
        run: find -name "*.html" | xargs djhtml -c
        working-directory: .
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install Dependencies
        run: pip3 install twine check-manifest -Ue .
      - name: Run check-manifest
        run: check-manifest .
        working-directory: .
      - name: Build package
        run: python -m build
        working-directory: .
      - name: Check package
        run: twine check dist/*
        working-directory: .
